### ISSUE TITLE
curl.setOption(CURLOPT_POSTFIELDS) causes use-after-free of the fields parameter

### ISSUE THREAD

**Issue by zhuowei** [PerfectlySoft/Perfect#115]
It seems that Curl doesn't make a copy of the post fields, so once setOption returns the CString is gone and curl reads garbage from the heap instead.

**Comment by C0deH4cker** [comment]
It appears that the only place this problem is encountered is [PerfectLibTests.swift](https://github.com/PerfectlySoft/Perfect/blob/635e84675be008148bc6cb97433bb91a7488e314/PerfectLib/PerfectLibTests/PerfectLibTests.swift#L714). Therefore, it's not a critical security flaw, though it might cause tests to fail in certain cases. Obviously it needs to be fixed. The data should either be copied or made global so it's not invalidated upon return from the function.

**Comment by kjessup** [comment]
I added a comment to the code regarding how this operation works. I don't think it's practical to make copies of all such pointers so this is maybe the only thing to be done for now. I adjusted the test case accordingly.
