### ISSUE TITLE
Make separate repos for Server,PerfectLib,MySQL. MongoDB, etc.

### ISSUE THREAD

**Issue by generatronServer** [PerfectlySoft/Perfect#134]
This in order to make it easier to pull different dependencies into other projects

**Comment by SeanStephens** [comment]
This is a great idea. We have been tossing the idea back and forth for some time now - I'm glad someone suggested it out of the blue.

One of the core ideas of Perfect is ensuring that all of the core tools you need are instantly available in one toolbox when you drop it in place. When a mechanic or a plumber goes out to start work, they don't grab a pair of pliers, a hammer, etc. - they grab their toolbox. And there's nothing worse than when two years later when you go to build a similar project you can't figure out where that pesky tool is - when it wan't in your toolbox the whole time. Raw dependency hell is inescapable when thousands of versioned dependencies exist.

However, you also don't want to _remove_ tools from the toolbox because they are heavy or unnecessary - like a vacuum cleaner, or a saw-horse. So large, single-use tools should be separate pieces, to keep your code-base tight and clean.

I think the balance between a full-featured set of developer tools and "bloat" is always a tough balance. We should adhere to value of "out of the box simplicity", or "ease of use", over "fractionalization for the sake of claiming to be light-weight and modular".

Certainly the following should be independent repos, to keep the main library light-weight: **Datasource Connectors** and **Examples**. One question, up for discussion, is whether the server should be separated. Being able to serve is somewhat integral.

Also, the intent to modularize should include compatibility with the Swift Package Manager, once it can handle dynamic libraries, which [should be available in due course](https://github.com/apple/swift-package-manager).

**Comment by generatronServer** [comment]
Server+PerfectLib, Individual Connectors, Examples. Thinking on stuff that in the future you can easily integrate with the package manager.

**Comment by SeanStephens** [comment]
We've had some great advice balancing the importance of modularization with the philosophy of Pristine Sources. (https://en.wikipedia.org/wiki/Pristine_Sources). If we are to remain Perfect, we should limit over-modularization. We need to carefully consider those who "forget how to program" (http://www.haneycodes.net/npm-left-pad-have-we-forgotten-how-to-program/). 

Certainly expect some core components to be separated - but the core of Perfect should remain robust and feature-rich.

Just a thought.

**Comment by ejohnsonw** [comment]
I posted the request under the @generatronServer account. Modularization like anything we do in extreme can be counterproductive. 

I would not put the blame of what happened on modularization  but on a package manager that allows dependencies to become unavailable. 

I read the article a few days ago and I think the spirit of it is why are we so dependent on libraries for the most trivial things or for core functionality of our products (which is what the Pristine Sources article mentions).

Back to the request,  I think our main need was to be able to use package manager to make things easy for the application generator to assemble things.  I know there are some restrictions related to dynamic libs.

Really appreciate all the time you guys have put into building Perfect, by building Generatron we hope to increase the rate of adoption of Perfect by making building things easy.

If not ready to move in that direction feel free to close this issue.

**Comment by kjessup** [comment]
We've made great progress with the newer builds of the Swift PM and have been splitting the components into their own repositories. They are mostly all private at the moment but we will be opening them up over the next few days. The MySQL connector has already been massaged to build with SPM and placed in its own repo.

**Comment by ejohnsonw** [comment]
Thank you @kjessup
