### ISSUE TITLE
Tutorial Contest Entry - Introduction to Perfect Video Series

### ISSUE THREAD

**Issue by rymcol** [PerfectlySoft/Perfect#164]
# Hi Everyone!

I have been hard at work learning _Perfect_ and making tutorial videos in my spare time. This is by far not finished yet, but since the introduction section is done, I figured it was time to share it with the community. 

## So beginning today I have four videos for you:

1. How to setup an Xcode Workspace (HelloPerfect Part 1): https://www.youtube.com/watch?v=LNU6L2pnq0k
2. How to host your first Web Application with a custom route (Hello Perfect Part 2): https://www.youtube.com/watch?v=rYV9M64pPv8
3. How to host web content (a website) with Perfect: https://www.youtube.com/watch?v=J441eJ40PH4
4. How to host dynamic content using Mustache Templates and Handlers: https://www.youtube.com/watch?v=SX9aX2aYzpw

## Update: May 5th:

Video 5 is live!

5. How to encode JSON: https://youtu.be/EwoXL_ZnA3s

I have also combined them into one easy playlist here: https://www.youtube.com/playlist?list=PLE2M81Pddau3LrJRGPbc6UXMy3VQuA2lL

## Update: May 6th:

Video 6 is live!

6. Start working with POST requests: https://youtu.be/IwkbRxDZaBA

## More to Come

Again, this is only the beginning for me as I prepare an entire online course in everything Perfect has to offer. Things I have planned: 

- How to hookup a database and work with the database connectors
- How to use Perfect's built-in JSON
- How to create a Private API & an iOS app that uses that API
- How to create a public API
- How to work with Perfect's built-in curl library
- How to tie all of it together in one application (an API, web app, mobile app, database, custom routes, and mustache as one project)

### If you like my tutorials, please give hit the like button in the upper right corner (looks like +😀) and select the "thumbs up" to vote for me in the competition, and thank you for watching!

Edit: Made Voting Instructions More Clear
Edit 2: Added Video 5: Encoding JSON
Edit 3: Added Video 6: Working with POST

**Comment by rymcol** [comment]
If this gets popular enough, I will also do the same for Ubuntu and make a couple videos on deployment using a platform (AWS, Docker, Heroku)

**Comment by yuppielabel** [comment]
I would really know how to set it up with Apple Server 5.1 with TLS. A tutorial setting up that would bee great.

**Comment by rymcol** [comment]
@yuppielabel Noted. I have a few Mac Mini's pretending to be servers in my closet. I will add that to my curriculum as a "production environment" series.

**Comment by rymcol** [comment]
## Connect with me

If anyone would like to connect with me you can find my social links at http://ryanmcollins.com/

**Comment by miwand** [comment]
Awesome work, was really easy to follow. Got me excited for more.

**Comment by rymcol** [comment]
@miwand Thanks a bunch!

**Comment by dnunez32** [comment]
Fantastic work on this Ryan.

**Comment by HardcoreIOS** [comment]
Great job!

**Comment by rymcol** [comment]
@dnunez32 @HardcoreIOS Thanks!

**Comment by qizt** [comment]
Thank you for the tutorial, can't wait for the build-in JSON part.

I've encountered this error in encoding dictionary: https://github.com/PerfectlySoft/Perfect/issues/165

Do you have any idea what the problem of my way is?

**Comment by rymcol** [comment]
@qizt I posted a solution that you can use for you situation on #165

**Comment by rymcol** [comment]
# Encoding JSON!

Issue #165 by @qizt had a good question: "How do I encode JSON"

This was a relatively short topic, so I took some time on my lunch break today to try to answer that in context with how it was asked in a New Video.

You can watch it at: https://youtu.be/EwoXL_ZnA3s

Thanks!

**Comment by kingiol** [comment]
@rymcol awesome， Thanks a lot

**Comment by qizt** [comment]
@rymcol Thank you for the video with JSONEncoder!

Here I have some suggestion.

<img width="459" alt="screen shot 2016-05-06 at 01 53 56" src="https://cloud.githubusercontent.com/assets/7324708/15066269/898896b6-132d-11e6-86dc-6aec2c703113.png">
Above is a snippet of code from your video, you traversed the array `cars` to encode car objects.
You were totally right, because type of `cars` is `[[String: JSONValue]]`, it cannot be encoded. JSONEncoder doesn't accept such dictionary type.

However, JSONEncoder accepts `[JSONValue]` according to PerfectLib documents.

So what I want to say is I have a elegant way encoding an array other than traversing it:
The trick is just declaring objects array `cars` as `[JSONValue]`, then it can be encoded.

So code would be:
<img width="440" alt="screen shot 2016-05-06 at 02 04 16" src="https://cloud.githubusercontent.com/assets/7324708/15066454/dd6735f2-132e-11e6-86fd-7f8d13bcd21d.png">

And the respond would be:
<img width="273" alt="screen shot 2016-05-06 at 02 03 28" src="https://cloud.githubusercontent.com/assets/7324708/15066471/f64805ba-132e-11e6-99fc-c526e64b4806.png">

Format is also pretty good, because the array is encoded into JSON string directly.

What I did is just add a type declaration into this line of code: 
`let cars = [car1, car2]`
⬇️
`let cars: [JSONValue] = [car1, car2]`

So what I've learnt from this is: 
JSONEncoder can really encode either Dictionary or Array. But the value must be declared as `JSONValue`.

**Comment by rymcol** [comment]
@qizt That's fantastic. Really shortens things! I will have to make an update to the video series soon.

**Comment by rymcol** [comment]
# Using http POST!

Another day, another video!

Get started handling POST in Perfect: https://youtu.be/IwkbRxDZaBA

**Comment by LucasC53** [comment]
You are a MACHINE, @rymcol!

**Comment by rymcol** [comment]
@LucasC53 definitely

**Comment by rymcol** [comment]
As the contest is over, I have closed this thread. You can follow my future tutorials on http://perfect.org/tutorials.html

**Comment by soloshenko** [comment]
About Encoding JSON!
I think this method works better:
func serialization(object:AnyObject) -> [UInt8]
{
do {
let jsonData = try NSJSONSerialization.dataWithJSONObject(object, options: NSJSONWritingOptions.PrettyPrinted)
let count = jsonData.length / sizeof(UInt8)
var jsonArray = [UInt8](count: count, repeatedValue: 0)
jsonData.getBytes(&jsonArray, length:count * sizeof(UInt8))
return jsonArray

} catch let error as NSError {
print(error)
}

Then:
    func handleRequest(request: WebRequest, response: WebResponse)
    {
        let car1:[JSONKey: AnyObject] = ["Wheel":4, "Color":"Black"]
        let car2:[JSONKey: AnyObject] = ["Wheel":3, "Color":["mixColor":0xf2f2f2]]
        let cars                      = [car1, car2]
        response.appendBodyBytes(serialization(cars))
        response.requestCompletedCallback()
    }

Details look this: https://habrahabr.ru/post/283260/
Sorry, this article in Russain.

![image09](https://cloud.githubusercontent.com/assets/1788577/15152041/8da8c420-16dc-11e6-8b79-d8b54980cc53.jpg)

**Comment by robertBojor** [comment]
Unless you are planning to run the backend on a Mac, anything NS related
will not work on a Linux machine.

I have deployed my test API on Heroku last night and I had to move away
from any NS related methods and types in order to succsessfuly compile the
code.

On Tuesday, 10 May 2016, soloshenko <notifications@github.com> wrote:

> About Encoding JSON!
> I think this method works better:
> func serialization(object:AnyObject) -> [UInt8]
> {
> do {
> let jsonData = try NSJSONSerialization.dataWithJSONObject(object, options:
> NSJSONWritingOptions.PrettyPrinted)
> let count = jsonData.length / sizeof(UInt8)
> var jsonArray = UInt8
> jsonData.getBytes(&jsonArray, length:count * sizeof(UInt8))
> return jsonArray
>
> } catch let error as NSError {
> print(error)
> }
>
> Then:
> func handleRequest(request: WebRequest, response: WebResponse)
> {
> let car1:[JSONKey: AnyObject] = ["Wheel":4, "Color":"Black"]
> let car2:[JSONKey: AnyObject] = ["Wheel":3, "Color":["mixColor":0xf2f2f2]]
> let cars = [car1, car2]
> response.appendBodyBytes(serialization(cars))
> response.requestCompletedCallback()
> }
>
> Details look this: https://habrahabr.ru/post/283260/
> Sorry, this article in Russain.
>
> [image: image09]
> <https://cloud.githubusercontent.com/assets/1788577/15152041/8da8c420-16dc-11e6-8b79-d8b54980cc53.jpg>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/PerfectlySoft/Perfect/issues/164#issuecomment-218193201>
>


-- 
Kind regards,
Robert Bojor
Mobile & Web Developer
http://www.robertbojor.com/

**Comment by rymcol** [comment]
@soloshenko @robertBojor is correct, while NSJSONSerialization is perfectly fine on the Mac for OS X/iOS, it will not work on Ubuntu, so the preferred method is to use Perfect's internal library. Also, the point of the tutorial is not to teach NSJSON and other framework methods, but to teach the methods included with Perfect.

**Comment by soloshenko** [comment]
@robertBojor @rymcol **You are right.**

**Comment by keyOfVv** [comment]
@rymcol awesome tutorials! Any tutorial how to integrate Perfect-MongoDB connector on Linux machine?

**Comment by rymcol** [comment]
@keyOfVv Thanks! I have not yet started any for Linux yet, I've been focusing on OS X. I will do a separate series eventually on Ubuntu.

**Comment by rymcol** [comment]
If anyone is still following this, the latest video is up: https://www.youtube.com/watch?v=T7URx9ngivk
