### ISSUE TITLE
BuildingPerfectTemplate in Ubuntu 14.04 in AWS with swift 3.0 latest development build 

### ISSUE THREAD

**Issue by dsp1589** [PerfectlySoft/Perfect#190]
Guys am trying to build perfecttemplate project by following steps in "https://github.com/PerfectlySoft/Perfect" in AWS Ubuntu-14.04 instance after installing swift 3.0 developer version. m getting this build error. I managed to clear other errors like openssl.

Here is the error message. from the error message, Am clear that Filter is missing the type None.

Compile Swift Module 'PerfectNet' (5 sources)
/home/ubuntu/PerfectTemplate/Packages/PerfectNet-0.8.0/Sources/NetEvent.swift:198:20: error: type 'NetEvent.Filter' has no member 'None'
                                                var filter = Filter.None
                                                             ^~~~~~ ~~~~

what is going wrong here?

**Comment by dsp1589** [comment]
Am seeing this Filter enum dont have "None". 
enum Filter {
		case none, error(Int32), read, write, timer

**Comment by taplin** [comment]
hmm, and the lowercase looks consistent… 
good find.

Can you confirm that changing the code in NetEvent.swift to lowercase the Filter member fixes the issue? I would assume that is where it will need to be fixed.

Tim Taplin

**Comment by dsp1589** [comment]
@taplin what do you mean by confirmation. Honestly, If someone already working with Perfectly swift project confirm it would be better. I just started today, good day :)

**Comment by timurkhab** [comment]
@taplin I confirm error been fixed replacing Read, Write, None, Error, Timer with lowercase. Ubuntu 16.04

**Comment by kjessup** [comment]
We are trying to take care of making our APIs conform to the Swift API guidelines before our next official release, which should correspond with Swift 3.0's release. As such, all enum values were changed to be lower case.

If you are seeing weird issues with compiling the Net, Thread or PerfectLibs, try a `swift build --clean=dist` and then try building again to see if simply fetching the most up-to-date versions does not fix the problem in the libs, noting that you may still have to update your code to match.

Our goal is to get all such breaking changes out of the way now so that we can have smoother updates post Swift 3.0.

**Comment by kjessup** [comment]
This is fixed now on all platforms. I get proper builds on OS X, U15 & U14.
