### ISSUE TITLE
Slow response time

### ISSUE THREAD

**Issue by WCByrne** [PerfectlySoft/Perfect#204]
Just getting started with Perfect but immediately noticed the response times on localhost were slow, around 5 seconds. 

Digging around I noticed `oldCompletion` was not getting called after the handling was complete. 
This line here: https://github.com/PerfectlySoft/Perfect/blob/master/Sources/PerfectLib/HTTPServer.swift#L275

I replaced that with the contents of that block `request.connection.close()` and request times are back down to the expected (near instant 👍)

Am I missing something or is this an issue in the lib?

**Comment by kjessup** [comment]
Yes! This has been fixed in master but hasn't been tagged yet. It's a regression after refactoring and shifting around the HTTP request response objects. Response is not setting the content-length properly. I'm trying to track down another issue when serving large files through byte ranges, after which I will tag this fix. Good catch, thank you.

**Comment by kjessup** [comment]
Committed. Change was tagged and will be picked up with a swift build --clean=dist
