### ISSUE TITLE
Perfect + Foundation on Ubuntu server

### ISSUE THREAD

**Issue by Codeido** [PerfectlySoft/Perfect#205]
First of all, thanks for your exceptional work, i think that Perfect will change the future of writing backend code.

Then, i have a problem.
I don't know if the swift snapshot on ubuntu contain the Foundation framework or not. I use in my project Foundation on macOS with no problems, but when i put the code on my Ubuntu server that has the same snapshot version of Swift that i have installed on my mac, URLSession is not found.

You have any suggestions? Is foundation that is not present or something wrong?

Thanks
-Paolo

**Comment by Codeido** [comment]
After investigating, i think that the actual version of Foundation used in Xcode 8 is the last version, but the linux version use an old version. For example, i use on Xcode URLSession, but on ubuntu there is an error during compiling. If i use NSURLSession there is no errors here.

Any suggestions?

Thanks,
-Paolo

**Comment by rymcol** [comment]
@Codeido The foundation library that is present in Xcode is not the same as the Foundation that is on Linux. The Foundation on Xcode is still part of the private source of cocoa, while the new one (#import SwiftFoundation) is separate, only on linux. They share the same goals, but for now they're different and not guaranteed to work exactly the same way. Hopefully down the road they merge them and stop maintaining two different code bases for the same functions. 

Also on Swift 3, depending on what build you're using, they've started renaming the base classes without the NS prefixes. It's now URLSession. See: https://www.dropbox.com/s/3laorscnmffsyi1/Screenshot%202016-07-01%2014.52.44.png?dl=0

And keep in mind since there are different Foundations, there may be a delay in the renaming on one or both. So it could be URLSession on both, or one of them might be stuck on NSURLSession until the next update.

**Comment by rymcol** [comment]
You should be able to use #if os(Linux) statements to separate them for now if you need to compile on both, but the amount of work you need to make that work may outweigh just waiting for the next snapshot.

**Comment by Codeido** [comment]
Then, i have to wait for the next snapshot.
Thank you so much for the great explanation @rymcol.

**Comment by rymcol** [comment]
@Codeido No problem.
