### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by lsolniczek** [PerfectlySoft/Perfect#23]
Hi, I can't find in doc. How I can handle routing with Perfect?

**Comment by makoni** [comment]
Looks like there's now routing out of box and you should implement it by yourself using WebRequest class.

It would be great to add router like in Express.js

**Comment by lsolniczek** [comment]
If someone, more advanced in Perfect, start working on Routing I could gladly help.

**Comment by brado** [comment]
"Looks like there's routing out of the box"

If you are referring to routing to the top-level moustache file only, then I suppose that would be "routing out of the box". But I'm not seeing anything to support routing in a true REST sense, paths with a hierarchy. Furthermore, after throwing the server through the debugger, it appears that there may be a problem implementing routing, because rather than handling requests through what should be a controller, the "C" part of MVC, it appears it is relying on the view, the "V" part of MVC to bind to its handler. Changing this appears to require changing the innards of the HTTPServer, not a mere higher-layer handling or filter mechanism. 

This merits a completely separate issue be filed, which I will. But I'm having a hard time seeing from the source code where REST is substantially supported in Perfect. Maybe I'm just missing it, but I'm not seeing it in doc, nor in the examples, nor in the control flow shown when running the server in the debugger.

**Comment by kjessup** [comment]
The views can associate themselves with a handler name, but this is not associated with any particular class. A handler name is associated with a closure which can then return whatever class should handle the request; based on url or user agent, for example. You could potentially use different routing systems in this manner.

Alternately, one can register a global handler which will be called for any path which does not explicitly indicate a handler name. This is the hook through which higher level routing such as you are seeking would be added. I have it on the list to provide an example of this (I've done it before, but I want to make it nicer).

Using this global handler methodology, adding the handler pragma to the view itself would serve only as a sort of override.

However, there is a limitation currently in that the URL which is requested must exist as an actual file. Removing this is very high on the list and the required changes have already been mapped out.

Additionally, you should never have to alter the core HTTP of FastCGI server for this type of functionality. The WebResponse class drives most of this and it is abstracted away from the core server platform.

We are putting together more of a public roadmap so (potential) users can see where we currently intend to put our development time.

Thanks,
-Kyle

**Comment by kjessup** [comment]
I've just updated our development roadmap, which includes routing high on the list. [Perfect Roadmap](https://github.com/PerfectlySoft/Perfect/wiki/Perfect-Roadmap)

I'm going to keep this issue open for discussion.

**Comment by makoni** [comment]
"there's now routing out of box"

Oops, not "now", it had to be "no routing" :)

**Comment by brado** [comment]
Kyle -- thanks for the response! That sheds a little light on it for me. A few responses: 

"Alternately, one can register a global handler which will be called for any path which does not explicitly indicate a handler name. This is the hook through which higher level routing such as you are seeking would be added. I have it on the list to provide an example of this (I've done it before, but I want to make it nicer)."

If you could show me how to do this, that would help me tremendously. I have no problem for the time being writing routing myself -- but not being able to do it, that's going to be a problem. I have a project that has to move forward (like today) and if I can route it, I can use Perfect. If not, I can't. I don't need a downloadable, complete example. If you can post snippets to show me, I'd greatly appreciate it -- I can use those right now. 

"However, there is a limitation currently in that the URL which is requested must exist as an actual file. Removing this is very high on the list and the required changes have already been mapped out."

That's a very high priority, and really falls into the bigger picture of how to use Perfect as a REST framework: 

1. With respect to the quote above, we have to get that requirement removed. A response may not even have a visual representation or need a template -- it may just be starting some server-side behavior or returning programmatically-created JSON.

2. Related, I actually could not figure out how to get a file created for any kind of hierarchical resource. For example, (and I'm just using the Authenticator project as an example) I could create a file which would facilitate a /register path, but I couldn't figure out how to get a file which would satisfy a /register/help path. In other words, any level below the top level I wasn't able to figure out how to create a file to satisfy that...i.e. I doubted that routing was even possible, much less available. It would be good to know how to do this. 

3. In reading / tracing through source code, it appeared to me that only GET and POST HTTP methods were identified and handled. With respect to REST, it also requires PUT and DELETE method support. Also, in thinking about routing, routing shouldn't be solely dependent upon URL path, but also on the HTTP method as well, and possibly even the return Content-Type (application-json vs. text/html, for instance). 

While these are my immediate needs, I think these are also kind of bare-minimum requirements to be able to adequately claim to support REST as a framework. Without having web service support like this, I think Perfect will have a really hard time getting traction. 

I presently am in the process of embarking on development on several projects -- if I can handle routing (I'm fine to develop it myself if Perfect allows it) then I may be able to limp by for a short while, because I think that Swift represents such a huge value proposition. But without this, my hand is going to be forced to go another framework. Is there any way you can post fixes for any of these in the next day or two? What about the example which allows a global handler? Can you post code on that? If you want to hit me offline, feel free at brado@bighillsoftware.com. Thanks.

**Comment by brado** [comment]
One more note -- I mentioned this in my original post above, but I want to emphasize this. In tracing through the code, and in reading the doc associated with the examples (the Tap Tracker example) it appeared to me that the following is the processing path: 

mustache file template --> get handler class associated with handler name --> instantiate handler class --> invoke handler class's valuesForResponse method

If I'm understanding all of this correctly, according to the Model-View-Controller (MVC) pattern, the template really represents the View, the handler class represents the Controller, and any model classes would represent the model. If this is correct, this is essentially routing requests through the view (template), not the controller. 

I would propose that requests shouldn't be routed through views (mustache templates) to their controllers (handlers), but vice versa: the request should be routed first through its controller (handler) which then dispatches as necessary to its view (mustache templates), if it dispatches at all. 

Unless I am missing something, the template is really the View, but yet it is being given the stature of the controller -- it is dictating its own handling rather than the other way around, where the controller would dictate how it responds with a view. 

Here's a question -- is there any way to just simply get the request dispatched to a single controller class? The primary value of Perfect as I see it as of this moment is the Swift HTTP server, and secondarily the Swift DB connectors (though I confess I haven't used those yet). But there doesn't appear to be much in the way of web app framework or REST support here. I believe people would have a lot more leverage to use this immediately (I would) if the mustache template / handler stuff could just be bypassed entirely (i.e. it was merely one implementation of that single controller class which was optional), leaving developers with a hook where they could plug their own web app framework in. If there was a single hook through which all requests through (similar to a Java servlet, for example), that would let developers run immediately. What is there now appears to prevent much movement, without changing the base HTTP server implementation (which I have no interest in doing). 

Any chance of just getting the request routed to a controller which can be overridden?

**Comment by Danappelxx** [comment]
Hey @brado just wanted to note - I don't think Perfect is meant to make REST api's, think of it more as linking client & server. If you want to make an actual webapp in Swift, [Zewo](https://github.com/Zewo) is probably a better fit. Take a look at the [example](https://github.com/Zewo/Examples) to get a feel for it.

**Comment by brado** [comment]
@Danappelxx -- Here's the first sentence from the Perfect.org About page:

"What is Perfect?
Perfect is a framework for developing web and other REST services in the Swift programming language."

That seems pretty clear to me -- I've been engaging here as if that is the goal. As I mentioned above, I don't by any means know everything about it yet, but after spending a few days with it, as of its current state right at this moment, Perfect doesn't seem to be either a web framework or built to handle REST. I certainly want it to be that...so I'm just giving suggestions first for how to make it that, but second, how to let developers run freely in that direction until it officially becomes that.

Thanks for the recommendation of Zewo, I'll check it out!

Brad

**Comment by julien-c** [comment]
@brado Also check out [Swifter](https://github.com/glock45/swifter), I think it's pretty close to what you're looking for.

**Comment by kjessup** [comment]
@brado 

Answering a few of the questions here.
Regarding the global handler:
Check out `PageHandlerRegistry.addPageHandler(generator: PageHandlerGenerator)`. That adds a global "fallback" handler.

"With respect to the quote above, we have to get that requirement removed. A response may not even have a visual representation or need a template -- it may just be starting some server-side behavior or returning programmatically-created JSON."

I should have this completed today.

"Related, I actually could not figure out how to get a file created for any kind of hierarchical resource. For example, (and I'm just using the Authenticator project as an example) I could create a file which would facilitate a /register path, but I couldn't figure out how to get a file which would satisfy a /register/help path. In other words, any level below the top level I wasn't able to figure out how to create a file to satisfy that...i.e. I doubted that routing was even possible, much less available. It would be good to know how to do this."

I did it like so:

/register.mustache
/register/help.mustache

You could also do it like this:

/register/index.mustache
/register/help.mustache

"In reading / tracing through source code, it appeared to me that only GET and POST HTTP methods were identified and handled. With respect to REST, it also requires PUT and DELETE method support. Also, in thinking about routing, routing shouldn't be solely dependent upon URL path, but also on the HTTP method as well, and possibly even the return Content-Type (application-json vs. text/html, for instance)."

The system does not differentiate between methods. You can inquire as to the current method using WebRequest.requestMethod(). Routing based on the current method will be included. It won't have direct support for content-type based routing, however the system will be flexible enough that you can check the content type and dispatch to a different handler if desired.

Thanks,
-Kyle

**Comment by C0deH4cker** [comment]
@brado @Danappelxx I wouldn't recommend using Zewo, at least until they fix [this SQL injection vulnerability](https://github.com/Zewo/SQL/issues/1), unless your application doesn't need to use SQL.

Also, while I prefer Perfect in all other regards, Swifter definitely has Perfect beat when it comes to routing. Even though it doesn't appear to support routing based on request type (yet), it supports urls with path parameters as well as normal query parameters.

I am looking forward to the addition of proper routing in Perfect. Once it has that, I will for sure be using Perfect.

**Comment by Danappelxx** [comment]
Thanks for catching that, at @C0deH4cker! It's worth noting that the SQL Zewo repository was started 6 days ago - it's not mature yet. Come back in a few weeks and it should be ready. I urge you to take a look at the examples and consider how well designed it is to handle large applications - everything is very safe, composable, and fast. It also has a nice router, which I believe has even Swifter beat. Full disclosure - I am part of the Zewo team, though I haven't worked on the projects mentioned.

**Comment by C0deH4cker** [comment]
@Danappelxx I wasn't aware that you were involved in the Zewo project! I haven't spent much time looking at it, since I started by browsing the examples and the SQL injection vulnerability caught my eye. Is there a central description of the project, such as a webpage for it?

Also, does Zewo still beat Swifter after [this pull request I wrote](https://github.com/glock45/swifter/pull/79)?

**Comment by kjessup** [comment]
I committed the URL routing system along with an example project.

It currently supports method based routing, variables and wildcards. It does not rely on the mustache template system at all, so you can produce whatever sort of content you'd like in whatever manner you wish.

Feedback is of course appreciated!

Links to relevant code:
[Routing.swift](https://github.com/PerfectlySoft/Perfect/blob/master/PerfectLib/Routing.swift)
[Example PerfectHandlers.swift](https://github.com/PerfectlySoft/Perfect/blob/master/Examples/URL%20Routing/URL%20Routing/PerfectHandlers.swift)


Thanks,
-Kyle

**Comment by brado** [comment]
FYI -- swifter I believe added method-based routing yesterday. Thanks for the updates, Kyle, this is awesome, I'll take a look. I'm posting another issue about building on Linux which is of interest to me, as I've been Linux building Swifter and (without much success so far) CryptoSwift. Crypto is going to be a showstopper for server code on Linux until a stable library is available, I'm thinking, unless someone has it working already.

**Comment by makoni** [comment]
I'm sorry for offtop but what do you think about using self documented code? Using [VVDocumenter](https://github.com/onevcat/VVDocumenter-Xcode)?

**Comment by brado** [comment]
I don't always self document my code, but when I do, I use VVDocumenter (seriously -- I use it in Xcode).
