### ISSUE TITLE
PerfectLib compiled, but PerfectServer failed

### ISSUE THREAD

**Issue by justmark** [PerfectlySoft/Perfect#32]
Running on Ubuntu 14.04

As per the subject, PerfectLib compiled without error, but I get errors when trying to compile the Server.  Error is as follows:

clang++ -L/usr/local/swift-2.2/usr/lib/swift/linux -lFoundation -lswiftCore -lswiftGlibc /usr/local/lib/PerfectLib.so -Xlinker -rpath -Xlinker /usr/local/swift-2.2/usr/lib/swift/linux perfectserverfcgi.o -o perfectserverfcgi
/usr/local/lib/PerfectLib.so: undefined reference to `u_isalnum_55'
/usr/local/lib/PerfectLib.so: undefined reference to `udat_format_55'
/usr/local/lib/PerfectLib.so: undefined reference to `udat_close_55'
/usr/local/lib/PerfectLib.so: undefined reference to `u_isWhitespace_55'
/usr/local/lib/PerfectLib.so: undefined reference to `udat_open_55'
/usr/local/lib/PerfectLib.so: undefined reference to `u_errorName_55'
/usr/local/lib/PerfectLib.so: undefined reference to `ucal_getNow_55'
/usr/local/lib/PerfectLib.so: undefined reference to `udat_parse_55'
/usr/local/lib/PerfectLib.so: undefined reference to `u_isdigit_55'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [perfectserverfcgi] Error 1

Thanks

**Comment by kjessup** [comment]
Try the following and let me know what you see:

sudo updatedb
locate libicui18n.so

So far we have only built on 15.10. I'll start a 14.04 install now.

**Comment by justmark** [comment]
Thanks for the prompt reply!

libicu-dev was already installed.  Output of locate:

$ locate libicui18n.so
/usr/lib/x86_64-linux-gnu/libicui18n.so
/usr/lib/x86_64-linux-gnu/libicui18n.so.52
/usr/lib/x86_64-linux-gnu/libicui18n.so.52.1

**Comment by kjessup** [comment]
Ok, I see. Unfortunately, ICU appends the version number onto each function name. The ICU which gets installed on 15.10 is 5.5, thus the _55 at the end of the undefined functions.

I'll have to consider how to better handle this without forcing people to have to build ICU themselves as a dependency.

**Comment by justmark** [comment]
No worries, I can spin up a 15.10 instance.  Its all good - thanks for jumping on this so quickly.

**Comment by C0deH4cker** [comment]
I looked into this issue as I'm also hitting it on 14.04. It seems that Ubuntu is one of the only platforms where the libicu package is built with symbol renaming enabled, and the maintainer's reasoning behind this decision is discussed here: http://sourceforge.net/p/icu/mailman/icu-design/thread/20080618182302.2012566511.qww314159@motoko.argon.local/

I believe that the best solution for this issue is to include libicu sources and build a libicu.a as part of the build process for PerfectLib (and is linked into PerfectLib.so). I agree that it would be nice to avoid this. However, it seems that would cause more hassle than it's worth. Plus, relying on the system's libicu will likely cause instability seeing as the developers are so uncertain of the ABI compatibility that they added this crazy per-version symbol renaming "feature".

**Comment by C0deH4cker** [comment]
Continued looking into the issue, and here's what I found. The renaming in libicu comes from [urename.h](https://github.com/PerfectlySoft/Perfect/blob/12b0729c4e7f679d03c42565178c35bd5f2bd529/PerfectLib/linked/ICU/unicode/urename.h). Every symbol is `#define`ed to include the version suffix, for example it [defines `udat_open` to be `udat_open_55`](https://github.com/PerfectlySoft/Perfect/blob/12b0729c4e7f679d03c42565178c35bd5f2bd529/PerfectLib/linked/ICU/unicode/urename.h#L817) for libicu with major version 55. Therefore, C code using libicu is not subject to these naming issues, as you can and should just use the raw defines without the version suffix in C. This only works if we use the system's ICU headers, however, as they will have the macros providing the correct version suffix. This leads me to believe that the best approach is to provide a C function wrapper for any renamed libicu methods that should be used from Swift code (for example, `udat_open_wrapper`), and to rely on the system's libicu headers.

I did a bit of searching, and there aren't too many references to these renamed symbols in PerfectLib. Here's a summary of the references I found to renamed symbols in libicu from Swift code:

* [SessionManager.swift](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/SessionManager.swift)
    * Imported function [`ICU.ucal_getNow_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/SessionManager.swift#L28), but never used (looks like the code was later changed to instead use [`ICU.getNow()`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/SessionManager.swift#L225))
* [ICU.swift](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift)
    * [`u_isWhitespace_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L34)
    * [`u_isdigit_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L38)
    * [`u_isalnum_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L42)
    * [`ucal_getNow_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L59)
    * [`u_errorName_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L76)
    * [`udat_open_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L109) [another](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L153)
    * [`udat_close_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L115) [another](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L159)
    * [`udat_parse_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L118)
    * [`udat_format_55`](https://github.com/PerfectlySoft/Perfect/blob/e319ecfde078c2a08417eb1887d679a1d13827d3/PerfectLib/ICU.swift#L163)

So these listed functions need to be wrapped, and the system's headers need to be used instead of providing headers from a specific version.

I can continue working on this issue and submit a pull request if you'd like.

**Comment by C0deH4cker** [comment]
Oh, OS X doesn't provide headers for its `/usr/lib/libicucore.dylib` (which _does_ have all the functions we need). How fun.
