### ISSUE TITLE
The file "TapTracker" was not found.

### ISSUE THREAD

**Issue by jjjjjeffrey** [PerfectlySoft/Perfect#46]
i built the server and module, run the server:
![1](https://cloud.githubusercontent.com/assets/4246681/11949145/f548ced4-a8b6-11e5-833b-291ca8323792.png)

then i tap the button in Tap Tracker APP, its get this response:
Request succeeded with data Optional("The file \"/TapTracker\" was not found.")
JSON decoding failed with exception SyntaxError("Malformed boolean literal")

how can i resolve it?

**Comment by jjjjjeffrey** [comment]
i resolved it by copy 'TapTracker.mustache' file into webroot directory, but the server crashed when i tap the button in Tap Tracker APP:
![2](https://cloud.githubusercontent.com/assets/4246681/11949718/cd2e37c6-a8bc-11e5-88d1-4fd747e76c17.png)
is this a swift bug?
https://bugs.swift.org/browse/SR-175

**Comment by kjessup** [comment]
It's possible that it is the bug you linked to. When I run in lldb the last line of user code is in a catch where it attempts to print the exception that was thrown. It is curious why it is throwing an exception at all here though. I'll poke at it a bit more.

**Comment by kjessup** [comment]
This is corrected now. The crash was definitely caused by the bug you cite, and while I didn't fix that, I did correct the issue which was causing SQLite to throw the exception to begin with.

There seems to be an issue (not present on OS X) initializing global statics when a swift dll is loaded through dlopen.
