### ISSUE TITLE
self. is everywhere

### ISSUE THREAD

**Issue by ketzusaka** [PerfectlySoft/Perfect#89]
Throughout the codebase `self` is used to reference the current instance. This can lead to unexpected retain cycles.

When not explicitly referencing `self` at all times usage of an instance variable within a block will provide an error:

```swift
dispatch_async(queue) {
    print(myInstanceVariableReference)
}
```

This indicates to the developer that they must decide if they wish to retain `self`, or use a capture group to use it as weak or unowned.

Always using `self` results in not receiving this useful message, and can lead to bugs and retain cycles. Perfect should make use of the compilers tooling to help reduce bugs, especially since its intended to be deployed as a long-running task.

**Comment by ludagoo** [comment]
interesting... several days ago I was working on adding some functionality to Prefect and initially tried to reference the current instance and got a compiler error (I do not remember what it was) so I fixed it by adding self. Which I think was a compiler suggestion... after seeing your comments i went and tried it again and can not get it to act up. weird.

**Comment by califrench** [comment]
For reference, the syntax to prevent a retain cycle in a closure when referencing `self` is the following:
```swift
dispatch_async(queue) { [weak self] in 
    print(self?.myInstanceVariableReference)
}
```

Note that self is an optional because it may have been de-allocated by the time the closure runs.

Another option is to use `unowned` like so:
```swift
dispatch_async(queue) { [unowned self] in 
    print(self.myInstanceVariableReference)
}
```

But you may have a runtime error when self has been de-allocated, so the former is safer.

Please see [this Stack Overflow post](http://stackoverflow.com/questions/24042949/block-retain-cycles-in-swift "Block retain cycles in Swift?") for more information
